preset: laravel

enabled:
  - ordered_imports

disabled:
  - blank_line_before_return
  - concat_without_spaces
  - no_unneeded_control_parentheses
  - not_operator_with_successor_space
  - simplified_null_return
